version: "3.9"

services:
  app:
    build: .
    container_name: vsb-discord-bot
    env_file: .env
    environment:
      HTTP_PROXY: ""
      HTTPS_PROXY: ""
      ALL_PROXY: ""
      NO_PROXY: "*"
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: vsb-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
