name: Build & Push to Docker Hub

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]     # optional: build/push on version tags too
  pull_request:
    branches: [ main ] # build only (no push) for PRs

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    env:
      IMAGE_NAME: ${{ secrets.IMAGE_NAME || format('{0}/{1}', github.repository_owner, 'vsb-discord-bot') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU (multi-arch)
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Hub login
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata (tags/labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=ref,event=tag
            type=sha

      - name: Build (PR) / Build & Push (main/tags)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
